local wikilink = require("notes.wikilink")

describe("notes.wikilink", function()
	describe("cursor_pos_from_col", function()
		it("converts 0-based column to 1-based position", function()
			assert.equals(1, wikilink.cursor_pos_from_col(0))
			assert.equals(5, wikilink.cursor_pos_from_col(4))
			assert.equals(100, wikilink.cursor_pos_from_col(99))
		end)
	end)

	describe("last_open_start", function()
		it("finds last [[ before cursor", function()
			assert.equals(1, wikilink.last_open_start("[[link]]", 3))
			assert.equals(1, wikilink.last_open_start("[[link]]", 6))
			assert.equals(8, wikilink.last_open_start("before [[link]] after", 9))
		end)

		it("returns nil when no [[ exists before cursor", function()
			assert.is_nil(wikilink.last_open_start("text", 3))
			assert.is_nil(wikilink.last_open_start("a [[link]]", 1))
		end)

		it("handles multiple [[ on same line", function()
			assert.equals(7, wikilink.last_open_start("[[a]] [[b]]", 7))
			assert.equals(7, wikilink.last_open_start("[[a]] [[b]]", 11))
		end)

		it("handles nested brackets by finding the last opening before cursor", function()
			-- In "[[outer [[inner]] outer]]", position 12 is after "[[inner"
			-- The function finds the LAST [[ before cursor position 12, which is at position 9
			assert.equals(9, wikilink.last_open_start("[[outer [[inner]] outer]]", 12))
		end)

		it("handles multiple opening brackets", function()
			-- In "[[[link]]", the last [[ before position 5 is at position 1
			assert.equals(1, wikilink.last_open_start("[[[link]]", 5))
		end)
	end)

	describe("wikilink_bounds", function()
		it("finds complete wiki-link when require_close is true", function()
			local open, close = wikilink.wikilink_bounds("[[link]]", 4, true)
			assert.equals(1, open)
			assert.equals(7, close)
		end)

		it("returns nil when cursor is outside complete link", function()
			assert.is_nil(wikilink.wikilink_bounds("x[[link]]", 1, true))
			assert.is_nil(wikilink.wikilink_bounds("[[link]]", 9, true))
		end)

		it("finds incomplete wiki-link when require_close is false", function()
			local open, close = wikilink.wikilink_bounds("[[link", 5, false)
			assert.equals(1, open)
			assert.is_nil(close)
		end)

		it("returns nil when no [[ exists", function()
			assert.is_nil(wikilink.wikilink_bounds("text", 3, true))
		end)

		it("returns nil when cursor is after incomplete link", function()
			assert.is_nil(wikilink.wikilink_bounds("[[link]] after", 12, false))
		end)
	end)

	describe("closing_suffix", function()
		it("returns empty string when ]] is already present", function()
			assert.equals("", wikilink.closing_suffix("[[link]]", 6))
		end)

		it("returns ] when single ] is present", function()
			assert.equals("]", wikilink.closing_suffix("[[link]", 6))
		end)

		it("returns ]] when no closing bracket is present", function()
			assert.equals("]]", wikilink.closing_suffix("[[link", 6))
		end)

		it("handles cursor at different positions", function()
			assert.equals("]]", wikilink.closing_suffix("[[", 2))
			assert.equals("]]", wikilink.closing_suffix("[[a", 3))
		end)
	end)

	describe("wikilink_under_cursor", function()
		local function with_markdown_buf(fn)
			local buf = vim.api.nvim_create_buf(false, true)
			vim.api.nvim_set_current_buf(buf)
			local ok, err = pcall(fn, buf)
			if vim.api.nvim_buf_is_valid(buf) then
				vim.api.nvim_buf_delete(buf, { force = true })
			end
			if not ok then
				error(err)
			end
		end

		it("returns link text when cursor is inside [[...]]", function()
			with_markdown_buf(function()
				vim.api.nvim_set_current_line("[[link]]")
				vim.api.nvim_win_set_cursor(0, { 1, 3 })
				assert.equals("link", wikilink.wikilink_under_cursor())
			end)
		end)

		it("returns link text when cursor is on brackets", function()
			with_markdown_buf(function()
				vim.api.nvim_set_current_line("[[link]]")
				vim.api.nvim_win_set_cursor(0, { 1, 0 })
				assert.equals("link", wikilink.wikilink_under_cursor())
				vim.api.nvim_win_set_cursor(0, { 1, 1 })
				assert.equals("link", wikilink.wikilink_under_cursor())
				vim.api.nvim_win_set_cursor(0, { 1, 6 })
				assert.equals("link", wikilink.wikilink_under_cursor())
				vim.api.nvim_win_set_cursor(0, { 1, 7 })
				assert.equals("link", wikilink.wikilink_under_cursor())
			end)
		end)

		it("returns nil when cursor is outside wiki-link", function()
			with_markdown_buf(function()
				vim.api.nvim_set_current_line("[[link]] trailing")
				vim.api.nvim_win_set_cursor(0, { 1, 10 })
				assert.is_nil(wikilink.wikilink_under_cursor())
			end)
		end)

		it("returns nil for incomplete wiki-link", function()
			with_markdown_buf(function()
				vim.api.nvim_set_current_line("[[link")
				vim.api.nvim_win_set_cursor(0, { 1, 3 })
				assert.is_nil(wikilink.wikilink_under_cursor())
			end)
		end)

		it("returns nil for empty wiki-link", function()
			with_markdown_buf(function()
				vim.api.nvim_set_current_line("[[]]")
				vim.api.nvim_win_set_cursor(0, { 1, 2 })
				assert.is_nil(wikilink.wikilink_under_cursor())
			end)
		end)

		it("returns nil when link contains special characters", function()
			with_markdown_buf(function()
				vim.api.nvim_set_current_line("[[link|alias]]")
				vim.api.nvim_win_set_cursor(0, { 1, 3 })
				assert.is_nil(wikilink.wikilink_under_cursor())
			end)
		end)

		it("returns nil when link contains slashes", function()
			with_markdown_buf(function()
				vim.api.nvim_set_current_line("[[folder/link]]")
				vim.api.nvim_win_set_cursor(0, { 1, 3 })
				assert.is_nil(wikilink.wikilink_under_cursor())
			end)
		end)

		it("returns nil when link contains brackets", function()
			with_markdown_buf(function()
				vim.api.nvim_set_current_line("[[link[nested]]]")
				vim.api.nvim_win_set_cursor(0, { 1, 3 })
				assert.is_nil(wikilink.wikilink_under_cursor())
			end)
		end)

		it("handles multiple links on same line", function()
			with_markdown_buf(function()
				vim.api.nvim_set_current_line("[[first]] and [[second]]")
				vim.api.nvim_win_set_cursor(0, { 1, 3 })
				assert.equals("first", wikilink.wikilink_under_cursor())
				vim.api.nvim_win_set_cursor(0, { 1, 17 })
				assert.equals("second", wikilink.wikilink_under_cursor())
			end)
		end)

		it("handles nested brackets: extracts innermost link when cursor is inside it", function()
			with_markdown_buf(function()
				vim.api.nvim_set_current_line("[[outer [[inner]] outer]]")
				-- Cursor inside "inner" - should extract "inner"
				vim.api.nvim_win_set_cursor(0, { 1, 11 })
				assert.equals("inner", wikilink.wikilink_under_cursor())
			end)
		end)

		it("handles nested brackets: returns nil when in outer part after inner closes", function()
			with_markdown_buf(function()
				vim.api.nvim_set_current_line("[[outer [[inner]] outer]]")
				-- Cursor in "outer" after "[[inner]]" closes (position 19, in " outer")
				-- This finds last [[ at position 9, then ]] at 16, giving "inner]] outer"
				-- But link text contains ]], so it returns nil
				vim.api.nvim_win_set_cursor(0, { 1, 19 })
				assert.is_nil(wikilink.wikilink_under_cursor())
			end)
		end)

		it("returns nil for escaped brackets (current behavior)", function()
			-- Note: The current implementation doesn't check for escapes,
			-- so it will still find the link. We document this behavior.
			with_markdown_buf(function()
				vim.api.nvim_set_current_line("\\[[link]]")
				vim.api.nvim_win_set_cursor(0, { 1, 4 })
				assert.equals("link", wikilink.wikilink_under_cursor())
			end)
		end)
	end)

	describe("find_next_wikilink", function()
		it("finds next wikilink on same line", function()
			assert.equals(6, wikilink.find_next_wikilink("text [[link]]", 1))
			assert.equals(6, wikilink.find_next_wikilink("text [[link]]", 5))
		end)

		it("returns nil when no wikilink ahead", function()
			assert.is_nil(wikilink.find_next_wikilink("no link here", 1))
			assert.is_nil(wikilink.find_next_wikilink("[[link]] after", 10))
		end)

		it("finds next wikilink when cursor is inside current one", function()
			assert.equals(11, wikilink.find_next_wikilink("[[first]] [[second]]", 3))
		end)

		it("handles multiple wikilinks on same line", function()
			assert.equals(11, wikilink.find_next_wikilink("[[first]] [[second]] [[third]]", 1))
			assert.equals(11, wikilink.find_next_wikilink("[[first]] [[second]] [[third]]", 5))
			assert.equals(22, wikilink.find_next_wikilink("[[first]] [[second]] [[third]]", 13))
		end)

		it("finds wikilink immediately after cursor", function()
			assert.equals(2, wikilink.find_next_wikilink("x[[link]]", 1))
		end)
	end)

	describe("find_prev_wikilink", function()
		it("finds previous wikilink on same line", function()
			assert.equals(1, wikilink.find_prev_wikilink("[[link]] text", 10))
			assert.equals(1, wikilink.find_prev_wikilink("[[link]] text", 7))
		end)

		it("returns nil when no wikilink before cursor", function()
			assert.is_nil(wikilink.find_prev_wikilink("no link here", 5))
			assert.is_nil(wikilink.find_prev_wikilink("before [[link]]", 5))
		end)

		it("finds previous wikilink when multiple on line", function()
			assert.equals(1, wikilink.find_prev_wikilink("[[first]] [[second]]", 10))
			assert.equals(11, wikilink.find_prev_wikilink("[[first]] [[second]]", 15))
		end)

		it("handles multiple wikilinks on same line", function()
			assert.equals(1, wikilink.find_prev_wikilink("[[first]] [[second]] [[third]]", 10))
			assert.equals(11, wikilink.find_prev_wikilink("[[first]] [[second]] [[third]]", 20))
			assert.equals(22, wikilink.find_prev_wikilink("[[first]] [[second]] [[third]]", 25))
		end)

		it("does not return wikilink at cursor position", function()
			assert.is_nil(wikilink.find_prev_wikilink("[[link]]", 1))
			assert.equals(1, wikilink.find_prev_wikilink("[[link]]", 2))
		end)
	end)

	describe("wikilink_range", function()
		local function with_markdown_buf(fn)
			local buf = vim.api.nvim_create_buf(false, true)
			vim.api.nvim_set_current_buf(buf)
			local ok, err = pcall(fn, buf)
			if vim.api.nvim_buf_is_valid(buf) then
				vim.api.nvim_buf_delete(buf, { force = true })
			end
			if not ok then
				error(err)
			end
		end

		it("returns range when cursor is inside [[...]]", function()
			with_markdown_buf(function()
				vim.api.nvim_set_current_line("[[link]]")
				vim.api.nvim_win_set_cursor(0, { 1, 3 })
				local range = wikilink.wikilink_range()
				assert.is_table(range)
				assert.equals(0, range.line)
				assert.equals(2, range.start_col)
				assert.equals(3, range.end_col)
			end)
		end)

		it("returns nil when cursor is outside wiki-link", function()
			with_markdown_buf(function()
				vim.api.nvim_set_current_line("[[link]] trailing")
				vim.api.nvim_win_set_cursor(0, { 1, 12 })
				assert.is_nil(wikilink.wikilink_range())
			end)
		end)

		it("returns range for incomplete wiki-link", function()
			with_markdown_buf(function()
				vim.api.nvim_set_current_line("[[link")
				vim.api.nvim_win_set_cursor(0, { 1, 5 })
				local range = wikilink.wikilink_range()
				assert.is_table(range)
				assert.equals(0, range.line)
				assert.equals(2, range.start_col)
				assert.equals(5, range.end_col)
			end)
		end)

		it("returns correct line for multi-line buffer", function()
			with_markdown_buf(function()
				vim.api.nvim_buf_set_lines(0, 0, -1, false, { "line 1", "[[link]]", "line 3" })
				vim.api.nvim_win_set_cursor(0, { 2, 3 })
				local range = wikilink.wikilink_range()
				assert.equals(1, range.line)
			end)
		end)
	end)
end)
